version: '3'
services:

    php:
        image: jendbermejo/docker-php:7.2.1
        ports:
            - "9000:9000"
        volumes:
            - /home/docker/docker-demo/code:/var/www/html
        networks:
            - stockapp
        deploy:
            replicas: 2

    nginx:
        image: nginx:latest
        ports:
            - "10001:80"
        volumes:
            - /home/docker/docker-demo/code:/var/www/html
            - /home/docker/docker-demo/web/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - service-stock-mysql
        deploy:
            replicas: 4
        networks:
            - stockapp

    composer:
        image: composer:latest
        volumes:
            - /home/docker/docker-demo/code:/app
        command: install
        networks:
            - stockapp

    service-stock-mysql:
        image: mysql:5.7.22
        environment:
           - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - /home/docker/docker-demo/schema/database.sql:/docker-entrypoint-initdb.d/database.sql
        networks:
            - stockapp

networks:
    stockapp:
