version: '3.6'
services:

    php:
        image: 127.0.0.1:5000/php 
        ports:
            - "9000:9000"
        volumes:
            - ./stock-service:/var/www/html
        networks:
            - stockapp
        deploy:
            restart_policy:
               condition: on-failure 

    nginx:
        image: 127.0.0.1:5000/nginx
        ports:
            - "10001:80"
        volumes:
            - ./stock-service:/var/www/html
            - ./web/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php 
            - service-stock-mysql
        deploy:
            replicas: 2
        networks:
            - stockapp

    composer:
        image: 127.0.0.1:5000/composer
        volumes:
            - ./stock-service:/app
        command: install
        networks:
            - stockapp

    service-stock-mysql:
        image: 127.0.0.1:5000/mysql:5.7.22
        restart: always
        env_file:
           - ".env"
        environment:
           - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - ./data/db/mysql:/var/lib/mysql 
            - ./stock-service/database.sql:/docker-entrypoint-initdb.d/database.sql
        networks:
            - stockapp
      
networks:
    stockapp:
